nodeLinker: node-modules

enableGlobalCache: false

checksumBehavior: update

# Allow peer dependency warnings without failing
logFilters:
  - code: YN0086
    level: info
  - code: YN0002
    level: info

# Prevent lockfile modifications in CI/deployment
enableImmutableInstalls: false
