# Cloudflare Pages Configuration for PauseOne
name = "pauseone"
compatibility_date = "2024-01-15"

[env.production]
# Production environment configuration
vars = { NODE_ENV = "production" }

[env.staging]
# Staging environment configuration  
vars = { NODE_ENV = "staging" }

# Pages configuration
[pages]
# Build configuration
build_command = "npm run bundle:web"
build_output_dir = "dist"

# Custom headers and redirects are handled by _headers and _redirects files
# in the public directory or build output

# Environment variables for build process
[env.production.vars]
NODE_ENV = "production"
EXPO_PUBLIC_APP_ENV = "production"

[env.staging.vars]
NODE_ENV = "staging"
EXPO_PUBLIC_APP_ENV = "staging"
